server:
  port: 9091

spring:
  application:
    name: HOTEL-SERVICE

  config:
    import: configserver:http://localhost:9094
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

okta:
  oauth2:
    issuer: https://dev-33322530.okta.com/oauth2/default
    audience: api://default