server:
  port: 9093

spring:

  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
        - Path=/users/**

      - id: HOTEL-SERVICE
        uri: lb://HOTEL-SERVICE
        predicates:
        - Path=/hotels/**

      - id: RATING-SERVICE
        uri: lb://RATING-SERVICE
        predicates:
        - Path=/ratings/**



eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

okta:
  oauth2:
    issuer: https://dev-33322530.okta.com/oauth2/default
    audience: api://default
    client-id: 0oafn7eaof8xPBfWx5d7
    client-secret: z0cy6TBE7JbnZ9eK8e2XUcsfcvuMEz4DcwKE70uQeCUeahwlrN7qInFS70FFKi4b
    scopes: openid, profile, email, offline_access